services:
  # Base de datos MySQL
  db:
    image: mysql:8.0
    container_name: mysql_db
    restart: always
    environment:
      MYSQL_ROOT_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      MYSQL_DATABASE: ${MYSQL_DATABASE}
      MYSQL_USER: ${MYSQL_USER}
      MYSQL_PASSWORD: ${MYSQL_PASSWORD}
    ports:
      - "${MYSQL_PORT}:3306"
    volumes:
      - mysql_data:/var/lib/mysql
      - ./init.sql:/docker-entrypoint-initdb.d/init.sql
    networks:
      - app-network
    healthcheck:
      test: ["CMD", "mysqladmin", "ping", "-h", "localhost"]
      timeout: 20s
      retries: 10

# Backend FastAPI
  backend:
    build:
      context: ./backend
      dockerfile: Dockerfile
    container_name: fastapi_backend
    restart: always
    ports:
      - "${BACKEND_PORT}:8000"
    environment:
      DB_USER: root                        
      DB_PASSWORD: ${MYSQL_ROOT_PASSWORD}
      DB_HOST: db
      DB_PORT: 3306
      DB_NAME: ${MYSQL_DATABASE}
    depends_on:
      db:
        condition: service_healthy
    networks:
      - app-network
    volumes:
      - ./backend:/app

  # Frontend Angular
  frontend:
    build:
      context: ./frontend/usuarios-app
      dockerfile: Dockerfile
      args:
        ANGULAR_CLI_VERSION: ${ANGULAR_CLI_VERSION}
    container_name: angular_frontend
    restart: always
    ports:
      - "${FRONTEND_PORT}:4200"
    environment:
      API_URL: ${API_URL}
    depends_on:
      - backend
    networks:
      - app-network
    volumes:
      - ./frontend/usuarios-app:/app
      - /app/node_modules

volumes:
  mysql_data:

networks:
  app-network:
    driver: bridge